spring:
  application:
    name: Movie rest api
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:13306/movie_db
    username: exuser
    password: 88888888
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: user
      password: 99999999
    admin:
      name: admin
      password: 88888888
logging:
  level:
    '[com.example]': debug
    root: ERROR
  pattern:
    console: "%clr(%d{dd/MM E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
